apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
spec:
  capacity:
    storage: 10Gi  # Specify the size of the volume (10Gi in this case)
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  # The volume can be mounted by a single pod at a time
  persistentVolumeReclaimPolicy: Retain  # Keep the EBS volume even if PVC is deleted
  storageClassName: ebs-sc  # This should match the StorageClass defined in PVC
  awsElasticBlockStore:
    volumeID: vol-0be1acbb1a14deffc  # Replace with your actual EBS volume ID
    fsType: ext4  # Filesystem type (ext4 is commonly used)
    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce  # This must match the access mode of the PV
  resources:
    requests:
      storage: 10Gi  # Size of the volume requested
  storageClassName: ebs-sc  # Ensure this matches the StorageClass in the PV
